/*
* generated by Xtext
*/
package com.ericsson.ecim.yang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class YangOutlineTreeProvider extends DefaultOutlineTreeProvider {
    
}
