/*
 * generated by Xtext
 */
package com.ericsson.ecim.mgc;

import org.eclipse.xtext.conversion.IValueConverterService;

import com.ericsson.ecim.mgc.converters.StringValueConverter;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class JsonRuntimeModule extends
        com.ericsson.ecim.mgc.AbstractJsonRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return StringValueConverter.class;
    }

}
