/*
* generated by Xtext
*/
package com.ericsson.ecim.ui.contentassist;

import com.ericsson.ecim.ui.contentassist.AbstractOptionalityProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OptionalityProposalProvider extends AbstractOptionalityProposalProvider {

}
