/*
 * generated by Xtext
 */
package com.ericsson.ecim.yang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class YangUiModule extends com.ericsson.ecim.yang.ui.AbstractYangUiModule {
    public YangUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
