/*
 * generated by Xtext
 */
package com.ericsson.ecim.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OptionalityUiModule extends com.ericsson.ecim.ui.AbstractOptionalityUiModule {
    public OptionalityUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
