/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;

import TspMim.DescriptionType;
import TspMim.ExtensionType;
import TspMim.HideInConfdType;
import TspMim.HideInLdapType;
import TspMim.ParameterType;
import TspMim.ReducedLoggingAllowedType;
import TspMim.ReturnTypeType;
import TspMim.SensitiveType;
import TspMim.SystemMaintainedType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link TspMim.ActionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActionTypeValidator {
    boolean validate();

    boolean validateDescription(DescriptionType value);
    boolean validateExtension(EList<ExtensionType> value);
    boolean validateReturnType(ReturnTypeType value);
    boolean validateParameter(EList<ParameterType> value);
    boolean validateGroup(FeatureMap value);
    boolean validateSensitive(EList<SensitiveType> value);
    boolean validateReducedLoggingAllowed(EList<ReducedLoggingAllowedType> value);
    boolean validateHideInConfd(EList<HideInConfdType> value);
    boolean validateHideInLdap(EList<HideInLdapType> value);
    boolean validateSystemMaintained(EList<SystemMaintainedType> value);
    boolean validateName(Object value);
}
