/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;

import TspMim.AbstractType;
import TspMim.ActionType;
import TspMim.AttributeType;
import TspMim.BaseClassType;
import TspMim.DescriptionType;
import TspMim.ExtensionType;
import TspMim.ReducedLoggingAllowedType;
import TspMim.SingletonType;
import TspMim.SystemCreatedType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link TspMim.ClassType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassTypeValidator {
    boolean validate();

    boolean validateDescription(DescriptionType value);
    boolean validateExtension(EList<ExtensionType> value);
    boolean validateBaseClass(BaseClassType value);
    boolean validateAbstract(AbstractType value);
    boolean validateLdapObjectId(String value);
    boolean validateGroup(FeatureMap value);
    boolean validateSingleton(EList<SingletonType> value);
    boolean validateSystemCreated(EList<SystemCreatedType> value);
    boolean validateReducedLoggingAllowed(EList<ReducedLoggingAllowedType> value);
    boolean validateAttribute(EList<AttributeType> value);
    boolean validateAction(EList<ActionType> value);
    boolean validateName(Object value);
}
