/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;

import TspMim.BooleanType;
import TspMim.DateTimeType;
import TspMim.DescriptionType;
import TspMim.ExtensionType;
import TspMim.FloatType;
import TspMim.IntegerType;
import TspMim.LdapTypeInfoType;
import TspMim.SequenceType;
import TspMim.StringType;
import TspMim.StructType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TspMim.DataTypeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataTypeTypeValidator {
    boolean validate();

    boolean validateDescription(DescriptionType value);
    boolean validateExtension(EList<ExtensionType> value);
    boolean validateStruct(StructType value);
    boolean validateString(StringType value);
    boolean validateBoolean(BooleanType value);
    boolean validateInteger(IntegerType value);
    boolean validateDateTime(DateTimeType value);
    boolean validateFloat(FloatType value);
    boolean validateSequence(SequenceType value);
    boolean validateLdapTypeInfo(LdapTypeInfoType value);
    boolean validateName(Object value);
    boolean validateNameRef(Object value);
}
