/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;


/**
 * A sample validator interface for {@link TspMim.ExtensionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtensionTypeValidator {
    boolean validate();

    boolean validateExtender(Object value);
    boolean validateName(Object value);
    boolean validateRelease(Object value);
    boolean validateVersion(Object value);
}
