/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;

import TspMim.ClassType;
import TspMim.DataTypeType;
import TspMim.DescriptionType;
import TspMim.ExtensionType;
import TspMim.JimType;
import TspMim.RelationshipType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TspMim.MimType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MimTypeValidator {
    boolean validate();

    boolean validateDescription(DescriptionType value);
    boolean validateExtension(EList<ExtensionType> value);
    boolean validateJim(JimType value);
    boolean validateLdapObjectId(String value);
    boolean validateConfdTargetNamespace(String value);
    boolean validateDataType(EList<DataTypeType> value);
    boolean validateClass(EList<ClassType> value);
    boolean validateRelationship(EList<RelationshipType> value);
    boolean validateName(Object value);
    boolean validateRelease(Object value);
    boolean validateVersion(Object value);
}
