/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package TspMim.validation;

import TspMim.DataTypeType;
import TspMim.VoidType;

/**
 * A sample validator interface for {@link TspMim.ReturnTypeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReturnTypeTypeValidator {
    boolean validate();

    boolean validateVoid(VoidType value);
    boolean validateDataType(DataTypeType value);
}
