/*
 * generated by Xtext
 */
package com.ericsson.ecim.yang;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parser.IEncodingProvider;
import org.eclipse.xtext.service.DispatchingProvider;

import com.ericsson.ecim.yang.converters.YangValueConverter;
import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class YangRuntimeModule extends com.ericsson.ecim.yang.AbstractYangRuntimeModule {
    
    //Tell XText to use a special function for Value formatting
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return YangValueConverter.class;
    }
    
    //Tell XText to use a special function for UTF-8 encoding. This is needed to windows which has an odd character set
    //as default
    @Override
    public void configureRuntimeEncodingProvider(Binder binder) {
        binder.bind(IEncodingProvider.class)
              .annotatedWith(DispatchingProvider.Runtime.class)
              .to(UTF8EncodingProvider.class);
    }  
}