/*
* generated by Xtext
*/
package com.ericsson.ecim.yang.ui.contentassist;

import com.ericsson.ecim.yang.ui.contentassist.AbstractYangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class YangProposalProvider extends AbstractYangProposalProvider {

}
