#!/bin/sh

rm -rf eclipse-*.tar
rm -rf eclipse/

PAPYRUS_UPDATE_SITE="http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/1.0.2c/"
LUNA_UPDATE_SITE="http://download.eclipse.org/releases/luna/"
COMMON_DEPENDENCY_UPDATE_SITE="http://download.eclipse.org/recommenders/updates/stable/"
OCL_UPDATE_SITE="http://download.eclipse.org/modeling/mdt/ocl/updates/milestones/5.0.5/S201510060617/"

wget http://ftp.acc.umu.se/mirror/eclipse.org/technology/epp/downloads/release/luna/SR2/eclipse-standard-luna-SR2-linux-gtk-x86_64.tar.gz

tar xzf eclipse-standard-luna-SR2-linux-gtk-x86_64.tar.gz
rm -f eclipse-*.tar.gz

cd eclipse/

set -x
./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository ${PAPYRUS_UPDATE_SITE},${LUNA_UPDATE_SITE},${COMMON_DEPENDENCY_UPDATE_SITE} -installIU org.eclipse.papyrus.sdk.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository ${ECIM_TOOLCHAIN_REPOSITORY},${PAPYRUS_UPDATE_SITE},${OCL_UPDATE_SITE},${LUNA_UPDATE_SITE},${COMMON_DEPENDENCY_UPDATE_SITE} -installIU com.ericsson.ecim.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -uninstallIU com.ericsson.ecim.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -clean -purgeHistory

./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository ${ECIM_TOOLCHAIN_REPOSITORY},${PAPYRUS_UPDATE_SITE},${OCL_UPDATE_SITE},${LUNA_UPDATE_SITE},${COMMON_DEPENDENCY_UPDATE_SITE} -installIU com.ericsson.ecim.feature.feature.group,com.ericsson.ecim.coremw.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -uninstallIU com.ericsson.ecim.feature.feature.group,com.ericsson.ecim.coremw.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -clean -purgeHistory

./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository ${ECIM_TOOLCHAIN_REPOSITORY},${PAPYRUS_UPDATE_SITE},${OCL_UPDATE_SITE},${LUNA_UPDATE_SITE},${COMMON_DEPENDENCY_UPDATE_SITE} -installIU com.ericsson.ecim.feature.feature.group,com.ericsson.ecim.coremw.feature.feature.group,com.ericsson.ecim.vdicos.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -uninstallIU com.ericsson.ecim.feature.feature.group,com.ericsson.ecim.coremw.feature.feature.group,com.ericsson.ecim.vdicos.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -clean -purgeHistory

./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository ${ECIM_TOOLCHAIN_REPOSITORY},${PAPYRUS_UPDATE_SITE},${OCL_UPDATE_SITE},${LUNA_UPDATE_SITE},${COMMON_DEPENDENCY_UPDATE_SITE} -installIU com.ericsson.ecim.feature.feature.group,com.ericsson.ecim.coremw.feature.feature.group,com.ericsson.ecim.mmas.feature.feature.group,com.ericsson.ecim.cpp.feature.feature.group,com.ericsson.ecim.vdicos.feature.feature.group,com.ericsson.ecim.yang.feature.feature.group,com.ericsson.ecim.mgc.feature.feature.group,com.ericsson.ecim.stn.feature.feature.group

./eclipse -application org.eclipse.equinox.p2.director -noSplash -clean -purgeHistory

set +x 