/*
 * generated by Xtext
 */
package com.ericsson.ecim.mgc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends com.ericsson.ecim.mgc.ui.AbstractJsonUiModule {
    public JsonUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
