/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package imm.validation;

import imm.AttrDef;
import imm.Category;
import imm.RdnDef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link imm.ClassDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassDefValidator {
    boolean validate();

    boolean validateCategory(Category value);
    boolean validateRdn(RdnDef value);
    boolean validateAttr(EList<AttrDef> value);
    boolean validateName(String value);
}
