/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package imm.validation;

import imm.ClassDef;
import imm.ObjectDef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link imm.IMMContentsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IMMContentsTypeValidator {
    boolean validate();

    boolean validateClass(EList<ClassDef> value);
    boolean validateObject(EList<ObjectDef> value);
}
