/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package imm.validation;

import imm.AttrType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link imm.ObjectDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObjectDefValidator {
    boolean validate();

    boolean validateDn(String value);
    boolean validateAttr(EList<AttrType> value);
    boolean validateClass(String value);
}
