/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package imm.validation;

import imm.AttrFlags;
import imm.AttrValueType;
import imm.Category;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link imm.RdnDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RdnDefValidator {
    boolean validate();

    boolean validateName(String value);
    boolean validateType(AttrValueType value);
    boolean validateCategory(Category value);
    boolean validateFlag(EList<AttrFlags> value);
    boolean validateNtfid(long value);
}
