/*
* generated by Xtext
*/
package com.ericsson.ecim.mgc.ui.contentassist;

import com.ericsson.ecim.mgc.ui.contentassist.AbstractJsonProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JsonProposalProvider extends AbstractJsonProposalProvider {

}
