/*
 * generated by Xtext
 */
package com.ericsson.ecim;

import org.eclipse.xtext.conversion.IValueConverterService;

import com.ericsson.ecim.converters.StringValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OptionalityRuntimeModule extends com.ericsson.ecim.AbstractOptionalityRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return StringValueConverter.class;
    }

}
