/*
 * generated by Xtext
 */
package com.ericsson.ecim.yang.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.util.Pair;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class YangFormatter extends AbstractDeclarativeFormatter {
    
    @Override
    protected void configureFormatting(FormattingConfig c) {
    
        com.ericsson.ecim.yang.services.YangGrammarAccess f = (com.ericsson.ecim.yang.services.YangGrammarAccess) getGrammarAccess();
        
        //define the generic formatting
        //c.setAutoLinewrap(120);
        for(Pair<Keyword, Keyword> pair: f.findKeywordPairs("{", "}")) {
            c.setIndentation(pair.getFirst(), pair.getSecond());
            c.setLinewrap(1).after(pair.getFirst());
            c.setLinewrap(2).after(pair.getSecond());
        }    
        
        for(Keyword semiColon: f.findKeywords(";")) {
            c.setNoSpace().before(semiColon);
            c.setLinewrap(1).after(semiColon);
        }            
        
        
        c.setLinewrap(0, 1, 2).before(f.getSL_COMMENTRule());
        c.setLinewrap(0, 1, 2).before(f.getML_COMMENTRule());
        c.setLinewrap(0, 1, 1).after(f.getML_COMMENTRule());

        //assign some specific formatting rules
        c.setLinewrap(2).before(f.getBelongsToAccess().getBelongsToKeyword_0());
        c.setLinewrap(2).before(f.getRevisionAccess().getRevisionKeyword_0());
        
        // Property
        c.setNoSpace().before(f.getPropertyAccess().getColonKeyword_0_1());
        c.setNoSpace().after(f.getPropertyAccess().getColonKeyword_0_1());

        
        
        
        /*
        com.ericsson.yang.services.YangGrammarAccess gaccess = (com.ericsson.yang.services.YangGrammarAccess) getGrammarAccess();        
        


        c.setNoSpace().before(gaccess.getPropertyAccess().getColonKeyword_1());
        c.setLinewrap(1).before(gaccess.getPropertyAccess().getNamespaceAssignment_0());
        c.setNoSpace().after(gaccess.getPropertyAccess().getColonKeyword_1());
        
        // Module
        c.setLinewrap(1).after(gaccess.getModuleAccess().getLeftCurlyBracketKeyword_2() );
        c.setIndentation(gaccess.getModuleAccess().getLeftCurlyBracketKeyword_2(), 
                gaccess.getModuleAccess().getRightCurlyBracketKeyword_16());
        
        c.setLinewrap(2).before(gaccess.getModuleAccess().getNamespaceKeyword_4());
        c.setLinewrap(1).after(gaccess.getModuleAccess().getSemicolonKeyword_6());

        c.setLinewrap(2).before(gaccess.getModuleAccess().getDescriptionKeyword_12_0());
        c.setLinewrap(1).after(gaccess.getModuleAccess().getDescriptionKeyword_12_0());
        
        c.setLinewrap(2).before(gaccess.getModuleAccess().getContactKeyword_11_0() );
        c.setLinewrap(1).after(gaccess.getModuleAccess().getContactKeyword_11_0() );
        
        c.setLinewrap(2).before(gaccess.getModuleAccess().getOrganizationKeyword_10_0() );
        c.setLinewrap(1).after(gaccess.getModuleAccess().getOrganizationKeyword_10_0() );
        
        //Include
        c.setLinewrap(1).before(gaccess.getModuleAccess().getIncludeKeyword_9_0());
        c.setLinewrap(2).after(gaccess.getModuleAccess().getSemicolonKeyword_10_2());
        
        c.setLinewrap(1).before(gaccess.getModuleAccess().getRightCurlyBracketKeyword_16() );

        
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_3_2() );
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_10_2() );
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_11_2() );
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_12_2() );
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_13_2());
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_6() );
        c.setNoSpace().before(gaccess.getModuleAccess().getSemicolonKeyword_9_2() );
        
        // Submodule
        c.setLinewrap(1).after(gaccess.getSubModuleAccess().getLeftCurlyBracketKeyword_2() );
        c.setIndentation(gaccess.getSubModuleAccess().getLeftCurlyBracketKeyword_2(), 
                gaccess.getSubModuleAccess().getRightCurlyBracketKeyword_10());

        // SubModule sub constructs e.g. Belongs-To/Description/import/Augment
        c.setLinewrap(2).before(gaccess.getBelongsToAccess().getBelongsToKeyword_0());
        
        c.setLinewrap(2).before(gaccess.getSubModuleAccess().getDescriptionKeyword_7_0());
        c.setLinewrap(1).after(gaccess.getSubModuleAccess().getDescriptionKeyword_7_0());
        
        c.setLinewrap(2).before(gaccess.getImportAccess().getImportKeyword_0());
        c.setLinewrap(2).after(gaccess.getSubModuleAccess().getSemicolonKeyword_7_2());
        
        c.setLinewrap(2).before(gaccess.getSubModuleAccess().getIncludeKeyword_6_0());
        c.setLinewrap(2).after(gaccess.getSubModuleAccess().getSemicolonKeyword_6_2());
        
        c.setLinewrap(1).before(gaccess.getAugmentAccess().getAugmentKeyword_0());
        c.setLinewrap(2).after(gaccess.getAugmentAccess().getLeftCurlyBracketKeyword_2());
            
        // Import
        c.setLinewrap(1).before(gaccess.getImportAccess().getImportKeyword_0());
            
        // Leaf
        c.setIndentation(gaccess.getLeafAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getLeafAccess().getRightCurlyBracketKeyword_17()
        );
        c.setLinewrap(2).before(gaccess.getLeafAccess().getLeafKeyword_0());
        
        c.setLinewrap(1).before(gaccess.getLeafAccess().getTypeKeyword_5());
        c.setLinewrap(1).before(gaccess.getLeafAccess().getMandatoryKeyword_7_0());
        c.setLinewrap(1).before(gaccess.getLeafAccess().getDefaultKeyword_9_0());        
        c.setLinewrap(1).before(gaccess.getLeafAccess().getConfigKeyword_11_0());        
        c.setLinewrap(1).before(gaccess.getLeafAccess().getStatusKeyword_12_0());
        c.setLinewrap(1).before(gaccess.getLeafAccess().getDescriptionKeyword_13_0());        
        c.setLinewrap(1).before(gaccess.getLeafAccess().getReferenceKeyword_14_0());        
        
        c.setLinewrap(1).before(gaccess.getLeafAccess().getRightCurlyBracketKeyword_17());
        c.setLinewrap(2).after(gaccess.getLeafAccess().getRightCurlyBracketKeyword_17());
        
        // List
        c.setIndentation(gaccess.getListWithStatusAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getListWithStatusAccess().getRightCurlyBracketKeyword_18()
        );
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getLeftCurlyBracketKeyword_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_6_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_10_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_11_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_7_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_8_2());
        c.setLinewrap(1).after(gaccess.getListWithStatusAccess().getSemicolonKeyword_9_2());
        c.setLinewrap(2).after(gaccess.getListWithStatusAccess().getRightCurlyBracketKeyword_18());
        
        // Leaf-list
        c.setIndentation(gaccess.getLeafListAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getLeafListAccess().getRightCurlyBracketKeyword_21());
        c.setLinewrap(2).before(gaccess.getLeafListAccess().getLeafListKeyword_0());
        c.setLinewrap(1).after(gaccess.getLeafListAccess().getLeftCurlyBracketKeyword_2());
        c.setLinewrap(1).before(gaccess.getLeafListAccess().getTypeKeyword_5());
        c.setLinewrap(1).before(gaccess.getLeafListAccess().getMinElementsKeyword_12_0());
        c.setLinewrap(1).before(gaccess.getLeafListAccess().getMaxElementsKeyword_13_0());
        c.setLinewrap(1).before(gaccess.getLeafListAccess().getDescriptionKeyword_15_0());
        c.setLinewrap(1).before(gaccess.getLeafListAccess().getRightCurlyBracketKeyword_21());
        c.setLinewrap(2).after(gaccess.getLeafListAccess().getRightCurlyBracketKeyword_21());
        
        // Grouping
        c.setIndentation(gaccess.getGroupingAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getGroupingAccess().getRightCurlyBracketKeyword_7());
        c.setLinewrap(1).before(gaccess.getGroupingAccess().getRightCurlyBracketKeyword_7());
        c.setLinewrap(2).after(gaccess.getGroupingAccess().getRightCurlyBracketKeyword_7());
        
        // Container
        c.setIndentation(gaccess.getContainerAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getContainerAccess().getRightCurlyBracketKeyword_10());
        c.setLinewrap(2).before(gaccess.getContainerAccess().getContainerKeyword_0());
        c.setLinewrap(1).before(gaccess.getContainerAccess().getUsesKeyword_6_0());
        c.setLinewrap(1).before(gaccess.getContainerAccess().getDescriptionKeyword_5_0());
        c.setLinewrap(1).before(gaccess.getContainerAccess().getRightCurlyBracketKeyword_10());
        c.setLinewrap(2).after(gaccess.getContainerAccess().getRightCurlyBracketKeyword_10());        
        
        // Property
        c.setLinewrap(1).after(gaccess.getPropertyAccess().getSemicolonKeyword_4());
        
        // TypeDef
        c.setIndentation(gaccess.getTypeDefinitionAccess().getLeftCurlyBracketKeyword_2(),
                gaccess.getTypeDefinitionAccess().getRightCurlyBracketKeyword_11());
        c.setLinewrap(1).after(gaccess.getTypeDefinitionAccess().getLeftCurlyBracketKeyword_2());
        c.setLinewrap(1).before(gaccess.getTypeDefinitionAccess().getDescriptionKeyword_8_0());
        c.setLinewrap(1).before(gaccess.getTypeDefinitionAccess().getReferenceKeyword_9_0());
        
        c.setLinewrap(1).before(gaccess.getTypeDefinitionAccess().getRightCurlyBracketKeyword_11());
        c.setLinewrap(2).after(gaccess.getTypeDefinitionAccess().getRightCurlyBracketKeyword_11());
        
        // DataType
        c.setIndentation(gaccess.getDataTypeAccess().getLeftCurlyBracketKeyword_2_1_0(),
                gaccess.getDataTypeAccess().getRightCurlyBracketKeyword_2_1_6()
        );
        c.setLinewrap(1).after(gaccess.getDataTypeAccess().getLeftCurlyBracketKeyword_2_1_0());
        c.setLinewrap(2).after(gaccess.getDataTypeAccess().getRightCurlyBracketKeyword_2_1_6());

        // Enumeration
        c.setIndentation(gaccess.getEnumerationAccess().getLeftCurlyBracketKeyword_1(),
                gaccess.getEnumerationAccess().getRightCurlyBracketKeyword_4()
        );
        c.setLinewrap(1).after(gaccess.getEnumerationAccess().getLeftCurlyBracketKeyword_1());
        c.setLinewrap(2).after(gaccess.getEnumerationAccess().getRightCurlyBracketKeyword_4());
        
        // EnumLiteral
        c.setIndentation(gaccess.getEnumLiteralAccess().getLeftCurlyBracketKeyword_2_0_0(),
                gaccess.getEnumLiteralAccess().getRightCurlyBracketKeyword_2_0_5()
        );
        c.setLinewrap(1).after(gaccess.getEnumLiteralAccess().getRightCurlyBracketKeyword_2_0_5());
        
        c.setNoSpace().between(gaccess.getPropertyAccess().getNamespaceAssignment_0(), 
                gaccess.getPropertyAccess().getSemicolonKeyword_4());
        c.setNoSpace().between(gaccess.getPropertyAccess().getSemicolonKeyword_4(), 
                gaccess.getPropertyAccess().getNameAssignment_2());
        */
    }
}
